//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var User = newUserTable("recommendation", "user", "")

type userTable struct {
	mysql.Table

	// Columns
	UserID            mysql.ColumnInteger
	Email             mysql.ColumnString
	EncryptedPassword mysql.ColumnString
	Token             mysql.ColumnString
	CreatedAt         mysql.ColumnTimestamp
	UpdatedAt         mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type UserTable struct {
	userTable

	NEW userTable
}

// AS creates new UserTable with assigned alias
func (a UserTable) AS(alias string) *UserTable {
	return newUserTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserTable with assigned schema name
func (a UserTable) FromSchema(schemaName string) *UserTable {
	return newUserTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserTable with assigned table prefix
func (a UserTable) WithPrefix(prefix string) *UserTable {
	return newUserTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserTable with assigned table suffix
func (a UserTable) WithSuffix(suffix string) *UserTable {
	return newUserTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserTable(schemaName, tableName, alias string) *UserTable {
	return &UserTable{
		userTable: newUserTableImpl(schemaName, tableName, alias),
		NEW:       newUserTableImpl("", "new", ""),
	}
}

func newUserTableImpl(schemaName, tableName, alias string) userTable {
	var (
		UserIDColumn            = mysql.IntegerColumn("user_id")
		EmailColumn             = mysql.StringColumn("email")
		EncryptedPasswordColumn = mysql.StringColumn("encrypted_password")
		TokenColumn             = mysql.StringColumn("token")
		CreatedAtColumn         = mysql.TimestampColumn("created_at")
		UpdatedAtColumn         = mysql.TimestampColumn("updated_at")
		allColumns              = mysql.ColumnList{UserIDColumn, EmailColumn, EncryptedPasswordColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns          = mysql.ColumnList{EmailColumn, EncryptedPasswordColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return userTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:            UserIDColumn,
		Email:             EmailColumn,
		EncryptedPassword: EncryptedPasswordColumn,
		Token:             TokenColumn,
		CreatedAt:         CreatedAtColumn,
		UpdatedAt:         UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
