//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type User struct {
	UserID            int32 `sql:"primary_key"`
	Email             string
	EncryptedPassword string
	Token             string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}
